### PR TITLE
Add support for Laravel 10

### PR DESCRIPTION
**Pull request by SamuelNitsche**
This PR adds support for Laravel 10.

### CODE REVIEW

**Comment by hosamalzagh** [comment]
waiting

**Comment by acidjazz** [comment]
@Torann @dotpack @dwightwatson :) :) :)

**Comment by dwightwatson** [comment]
I'm not a maintainer on this repo, so can't help with this one I'm afraid. 

Would be happy to assist if the owner is open to it.

**Comment by acidjazz** [comment]
same - @Torann im happy to assist as well w/ @dwightwatson

**Comment by plakhin** [comment]
@SamuelNitsche, Laravel 10 requires `"phpunit/phpunit": "^10.0",`. Please update the PR.

**Comment by plakhin** [comment]
@Torann any hopes this will be merged soon?

**Comment by dwightwatson** [comment]
Just to be clear Laravel 10 supports PHPUnit 9 and 10, but also the dev dependencies of a package aren't relevant & won't prevent this package from being installed into a project.

**Comment by lptn** [comment]
@gtko 
Projects on  we constantly have issues with this package when we update Laravel or PHP, so we decided to fork it and use other another namespace. We keep using SemVer 2.0 and properly work with PRs, feel free to switch to that version and contribute to it: https://github.com/InteractionDesignFoundation/laravel-geoip

**Comment by jackkitley** [comment]
Any updates on this being merged?

**Review by DStainback — APPROVED** [review]

**Pull request merged**
